

--Tablespace Creation

CREATE TABLESPACE BSM_DEFAULT DATAFILE 'D:\APP\ACER\ORADATA\ORCL\BSM_DEFAULT.DBF' SIZE 100M;

CREATE TEMPORARY TABLESPACE BSM_TEMP TEMPFILE 'D:\APP\ACER\ORADATA\ORCL\BSM_TEMP.DBF' SIZE 30M;

--SCHEMA CREATION

CREATE USER BSM IDENTIFIED BY BSM DEFAULT TABLESPACE BSM_DEFAULT TEMPORARY TABLESPACE BSM_TEMP;

GRANT CONNECT,DBA TO BSM;

--CREATING DIRECTORY
CREATE DIRECTORY DATA_PUMP_BSM AS 'D:\app\Acer\admin\orcl\BSM';

GRANT READ, WRITE ON DIRECTORY DATA_PUMP_BSM TO BSM;

--TO DROP DIRECTORY
DROP DIRECTORY DATA_PUMP_BSM;

-- MST_ORG_DTLS
CREATE TABLE MST_ORG_DTLS(
    ORG_ID NUMBER CONSTRAINT PK_ORG_ID PRIMARY KEY,
    ORG_NAME VARCHAR2(30),
    ORG_PHONE_NUM NUMBER,
    ORG_MAIL_ID VARCHAR2(50),
    ORG_ADDRESS VARCHAR2(200),
    ORG_CP_NAME VARCHAR2(30),
    ORG_CP_MAIL_ID VARCHAR2(50),
    ORG_DEAL_DATE DATE,
    ORG_NO_OF_EMPLOYEES NUMBER,
    ORG_SALARY_DATE NUMBER,
    ORG_STATUS VARCHAR2(3)
);

-- SEQUENCE
CREATE SEQUENCE SEQ_ORG_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ORG_EMP_DTLS
CREATE TABLE ORG_EMP_DTLS (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    SALARY NUMBER,
    ORG_ID NUMBER,
    PHONE_NUM NUMBER,
    MAIL_ID VARCHAR2(50),
    DATE_OF_ACTIVE DATE,
    EMP_STATUS VARCHAR2(3),

    CONSTRAINT FK_ORG_ID 
        FOREIGN KEY (ORG_ID) 
        REFERENCES MST_ORG_DTLS(ORG_ID),

    CONSTRAINT PK_COMP_EMP_ID 
        PRIMARY KEY (EMP_ID, ORG_ID)
);


-------------------------------------------------------

--1.EXTERNAL TABLE [ EXT_MST_ORG_DTLS ]
CREATE TABLE EXT_MST_ORG_DTLS(
    ORG_ID NUMBER,
    ORG_NAME VARCHAR2(30),
    ORG_PHONE_NUM NUMBER,
    ORG_MAIL_ID VARCHAR2(50),
    ORG_ADDRESS VARCHAR2(200),
    ORG_CP_NAME VARCHAR2(30),
    ORG_CP_MAIL_ID VARCHAR2(50),
    ORG_DEAL_DATE DATE,
    ORG_NO_OF_EMPLOYEES NUMBER,
    ORG_SALARY_DATE NUMBER,
    ORG_STATUS VARCHAR2(3)
)
ORGANIZATION EXTERNAL 
( 
TYPE ORACLE_LOADER 
DEFAULT DIRECTORY DATA_PUMP_BSM
ACCESS PARAMETERS 
( 
  RECORDS DELIMITED BY NEWLINE SKIP 1
  NOBADFILE NODISCARDFILE NOLOGFILE 
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  MISSING FIELD VALUES ARE NULL

  (
    ORG_ID,
    ORG_NAME,
    ORG_PHONE_NUM,
    ORG_MAIL_ID,
    ORG_ADDRESS,
    ORG_CP_NAME,
    ORG_CP_MAIL_ID,
    ORG_DEAL_DATE DATE "DD-MM-YYYY",
    ORG_NO_OF_EMPLOYEES,
    ORG_SALARY_DATE,
    ORG_STATUS
  )
) 
LOCATION ('NEW_ORG.csv') 
) 
REJECT LIMIT UNLIMITED;

----------------------------------------
SELECT * FROM EXT_MST_ORG_DTLS;

-----------------------------------------

--2. EXTERNAL TABLE [ EXT_ORG_EMP_DTLS ]

CREATE TABLE EXT_ORG_EMP_DTLS (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    SALARY NUMBER,
    ORG_ID NUMBER,
    PHONE_NUM NUMBER,
    MAIL_ID VARCHAR2(50),
    DATE_OF_ACTIVE DATE,
    EMP_STATUS VARCHAR2(3)
)
ORGANIZATION EXTERNAL 
( 
TYPE ORACLE_LOADER 
DEFAULT DIRECTORY DATA_PUMP_BSM
ACCESS PARAMETERS 
( 
  RECORDS DELIMITED BY NEWLINE SKIP 1
  NOBADFILE NOLOGFILE NODISCARDFILE
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  MISSING FIELD VALUES ARE NULL
 
  (
    EMP_ID,
    EMP_NAME,
    SALARY,
    ORG_ID,
    PHONE_NUM,
    MAIL_ID,
    DATE_OF_ACTIVE DATE "DD-MM-YYYY",
    EMP_STATUS
  )
) 
LOCATION ('TCS.csv') 
) 
REJECT LIMIT UNLIMITED;
-------------------------------------------------
SELECT * FROM EXT_ORG_EMP_DTLS;

------------------------------------------------

--ERROR LOG TABLE 
create table ERROR_LOG
(
  program_name  VARCHAR2(30),
  error_date    DATE,
  error_msg     VARCHAR2(512),
  error_line_no VARCHAR2(100)
)

--ERROR LOG PROCEDURE.
CREATE OR REPLACE PROCEDURE SP_ERROR_LOG(P_PROGRAM_NAME VARCHAR2,
P_ERROR_MSG VARCHAR2,P_LINE_NO VARCHAR2)
AS
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO ERROR_LOG VALUES (P_PROGRAM_NAME,SYSDATE,P_ERROR_MSG,P_LINE_NO);
  COMMIT;
  END;

-----------------------------------------------



CREATE OR REPLACE PROCEDURE SP_DATA_MIGRATION AS
  X BOOLEAN;
  Y INTEGER;
  Z BINARY_INTEGER;

  LV_ORG_FILE VARCHAR2(500);
  LV_QUERY    VARCHAR2(1000);
  LV_ORG_NAME VARCHAR2(30);
  LV_EMP_FILE VARCHAR2(500);

  CURSOR C1 IS
    SELECT EM.ORG_NAME FROM EXT_MST_ORG_DTLS EM WHERE EM.ORG_STATUS='A';
    CURSOR C2 IS
    SELECT EM.ORG_NAME,EM.ORG_ID FROM EXT_MST_ORG_DTLS EM WHERE EM.ORG_STATUS='X';

BEGIN
  LV_ORG_FILE := 'NEW_ORG_DTLS_' || TO_CHAR(SYSDATE, 'DD_MM_YYYY') ||
                 '.CSV';
  UTL_FILE.fgetattr('DATA_PUMP_BSM', LV_ORG_FILE, X, Y, Z);

  IF X THEN
    LV_QUERY := 'ALTER TABLE EXT_MST_ORG_DTLS LOCATION ( ' || CHR(39) ||
                LV_ORG_FILE || CHR(39) || ' )';
    EXECUTE IMMEDIATE LV_QUERY;
  
    MERGE INTO MST_ORG_DTLS T
    USING EXT_MST_ORG_DTLS S
    ON (T.ORG_NAME = S.ORG_NAME)
    WHEN MATCHED THEN
      UPDATE
         SET T.ORG_CP_NAME         = S.ORG_CP_NAME,
             T.ORG_CP_MAIL_ID      = S.ORG_CP_MAIL_ID,
             T.ORG_NO_OF_EMPLOYEES = S.ORG_NO_OF_EMPLOYEES,
             T.ORG_SALARY_DATE     = S.ORG_SALARY_DATE,
             T.ORG_STATUS          = S.ORG_STATUS
    WHEN NOT MATCHED THEN
      INSERT
      VALUES
        (s.org_id,
         S.ORG_NAME,
         S.ORG_PHONE_NUM,
         S.ORG_MAIL_ID,
         S.ORG_ADDRESS,
         S.ORG_CP_NAME,
         S.ORG_CP_MAIL_ID,
         S.ORG_DEAL_DATE,
         S.ORG_NO_OF_EMPLOYEES,
         S.ORG_SALARY_DATE,
         S.ORG_STATUS);
  
  ELSE
    RAISE_APPLICATION_ERROR(-20333, 'ORGANIZATION FILE NOT FOUND');
  END IF;

  FOR I IN C1 LOOP
    LV_ORG_NAME := I.ORG_NAME;
  
    LV_EMP_FILE := LV_ORG_NAME || '_EMP_DTLS_' ||
                   TO_CHAR(SYSDATE, 'DD_MM_YYYY') || '.CSV';
    UTL_FILE.fgetattr('DATA_PUMP_BSM', LV_EMP_FILE, X, Y, Z);
  
    IF X THEN
      LV_QUERY := 'ALTER TABLE EXT_ORG_EMP_DTLS LOCATION ( ' || CHR(39) ||
                  LV_EMP_FILE || CHR(39) || ' )';
      EXECUTE IMMEDIATE LV_QUERY;
    
      MERGE INTO ORG_EMP_DTLS T
      USING EXT_ORG_EMP_DTLS S
      ON (T.EMP_ID = S.EMP_ID AND T.ORG_ID = S.ORG_ID)
      WHEN MATCHED THEN
        UPDATE SET T.SALARY = S.SALARY, T.EMP_STATUS = S.EMP_STATUS
      WHEN NOT MATCHED THEN
        INSERT
        VALUES
          (S.EMP_ID,
           S.EMP_NAME,
           S.SALARY,
           S.ORG_ID,
           S.PHONE_NUM,
           S.MAIL_ID,
           S.DATE_OF_ACTIVE,
           S.EMP_STATUS);
    
    ELSE
      RAISE_APPLICATION_ERROR(-20333, LV_ORG_NAME || ' EMP FILE NOT FOUND');
    END IF;
  END LOOP;
  
  FOR I IN C2 LOOP
    UPDATE ORG_EMP_DTLS OE SET OE.EMP_STATUS='X' WHERE OE.ORG_ID=I.ORG_ID;
    END LOOP;
EXCEPTION 
  WHEN OTHERS THEN
    sp_error_log('SP_DATA_MIGRATION',SQLERRM,DBMS_UTILITY.format_error_backtrace);
        RAISE_APPLICATION_ERROR(-20300, SQLERRM);

END SP_DATA_MIGRATION;


---------------------------------------------------
--JOB FOR SP_DATA_MIGRATION
DECLARE
  X NUMBER;
BEGIN 
  DBMS_JOB.SUBMIT(
    X,
    'BEGIN SP_DATA_MIGRATION; END;',
    TRUNC(SYSDATE) + 9/24,     
    'SYSDATE+1'
  );
  
  COMMIT;
END;
---------------------------------------------------


create table MONTHLY_SAL_CRD_DTLS
(
  org_name       VARCHAR2(30),
  crd_month      VARCHAR2(10), --WE WILL SHOW LIKE 'MAR'
  crd_year       NUMBER, --JUST YEAR, SO TAKEN NUMBER
  sal_gen_date   DATE,
  sal_crd_status VARCHAR2(3)
)

---------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_MONTHLY_SAL_CRD_DTLS AS
BEGIN
  DELETE FROM MONTHLY_SAL_CRD_DTLS;
  INSERT INTO MONTHLY_SAL_CRD_DTLS
    (ORG_NAME, CRD_MONTH, CRD_YEAR, SAL_GEN_DATE, SAL_CRD_STATUS)
  SELECT ORG_NAME,
         TO_CHAR(SYSDATE,'MM'),
         TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')),
         NULL,
         'P'
  FROM MST_ORG_DTLS
  WHERE ORG_STATUS = 'A';
  COMMIT;
END SP_MONTHLY_SAL_CRD_DTLS;

------------------------------------------------------
--JOB FOR SP_MONTHLY_SAL_CRD_DTLS;

DECLARE
  X NUMBER;
BEGIN 
  DBMS_JOB.SUBMIT(
    X,
    'BEGIN SP_MONTHLY_SAL_CRD_DTLS; END;',
    TRUNC(ADD_MONTHS(SYSDATE,1),'MM'), 
    'TRUNC(ADD_MONTHS(SYSDATE,1),''MM'')'
  );
  
  COMMIT;
END;

-------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_TOMORROW_SAL_FILES
AS
  FO UTL_FILE.FILE_TYPE;
  LV_ORG_FILE VARCHAR2(200);
  LV_EMP_FILE VARCHAR2(200);
  LN_TOTAL_SAL NUMBER;
  LN_EMP_COUNT NUMBER;
  LN_CNT NUMBER;
  
CURSOR C1 IS SELECT * FROM MST_ORG_DTLS OD
WHERE OD.ORG_STATUS = 'A' AND OD.ORG_SALARY_DATE = TO_CHAR(SYSDATE+1,'DD');

BEGIN
  SELECT COUNT(*) INTO LN_CNT FROM MST_ORG_DTLS OD
  WHERE OD.ORG_STATUS = 'A' AND OD.ORG_SALARY_DATE = TO_CHAR(SYSDATE+1,'DD');

  IF LN_CNT = 0 THEN
    RETURN;
  END IF;
  LV_ORG_FILE := 'ORG_LIST_FOR_SAL_CRD_' || TO_CHAR(SYSDATE,'DD_MM_YYYY') || '.CSV';

  FO := UTL_FILE.FOPEN('DATA_PUMP_BSM', LV_ORG_FILE, 'W');

  UTL_FILE.PUT_LINE(FO,
    'ORG_NAME,ORG_PHONE,ORG_MAIL_ID,ORG_ADDRESS,ORG_CP_NAME,ORG_CP_MAIL,ORG_SAL_DATE');

  FOR I IN C1 LOOP
     UTL_FILE.PUT_LINE(FO,
      I.ORG_NAME || ',' ||
      I.ORG_PHONE_NUM || ',' ||
      I.ORG_MAIL_ID || ',' ||
      '"' || I.ORG_ADDRESS || '"' || ',' ||
      I.ORG_CP_NAME || ',' ||
      I.ORG_CP_MAIL_ID || ',' ||
      
      TO_CHAR(
        TO_DATE(
          I.ORG_SALARY_DATE || '-' || TO_CHAR(SYSDATE,'MM-YYYY'),'DD-MM-YYYY'),
        'DD-MM-YYYY'));

  END LOOP;

  UTL_FILE.FCLOSE(FO);

  FOR I IN C1 LOOP

    LV_EMP_FILE := I.ORG_NAME || '_EMP_SALARY_DTLS_' || TO_CHAR(SYSDATE,'DD_MM_YYYY') || '.CSV';

    FO := UTL_FILE.FOPEN('DATA_PUMP_BSM', LV_EMP_FILE, 'W');

    UTL_FILE.PUT_LINE(FO, 'EMP_ID,EMP_NAME,ORG_NAME,SALARY');

    
    LN_TOTAL_SAL:=0;
    LN_EMP_COUNT:=0;
    
    FOR J IN (SELECT EMP_ID, EMP_NAME, SALARY
      FROM ORG_EMP_DTLS OE WHERE OE.ORG_ID=I.ORG_ID AND OE.EMP_STATUS='A') LOOP

      UTL_FILE.PUT_LINE(FO,
        J.EMP_ID || ',' ||
        J.EMP_NAME || ',' ||
        I.ORG_NAME || ',' ||
        J.SALARY
      );

      LN_TOTAL_SAL := LN_TOTAL_SAL + J.SALARY;
      LN_EMP_COUNT := LN_EMP_COUNT + 1;

    END LOOP;

    UTL_FILE.PUT_LINE(FO,
      'EMP_COUNT'||',' || LN_EMP_COUNT || ','||'TOTAL_SAL'||','|| LN_TOTAL_SAL
    );

    UTL_FILE.FCLOSE(FO);

  END LOOP;

END SP_TOMORROW_SAL_FILES;



-------------------------------------------------
--JOB FOR SP_TOMORROW_SAL_FILES
DECLARE
  X NUMBER;
BEGIN 
  DBMS_JOB.SUBMIT(
    X,
    'BEGIN SP_TOMORROW_SAL_FILES; END;',
    TRUNC(SYSDATE) + 10/24,     
    'SYSDATE+1'
  );
  
  COMMIT;
END;


--------------------------------------------------


--NEW TABLES CREATION

CREATE TABLE MONTHLY_ORG_SAL_DTLS(ORG_ID NUMBER,
 MONTH NUMBER, YEAR NUMBER, TOTAL_SAL NUMBER, EMPLOYEES_COUNT NUMBER);

CREATE TABLE MONTHLY_ORG_SAL_STATUS( ORG_ID NUMBER, MONTH NUMBER, YEAR NUMBER,
  AMOUNT_DIFF NUMBER, EMPLOYEES_DIFF NUMBER,  MOTHLY_STATUS VARCHAR2(3));
  
SELECT * FROM MONTHLY_ORG_SAL_DTLS;
  
SELECT * FROM MONTHLY_ORG_SAL_STATUS;

--EXTERNAL TABLE FOR MONTHLY_ORG_EMP_DTLS

CREATE TABLE EXT_MONTHLY_ORG_EMP_DTLS (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    SALARY NUMBER,
    ORG_ID NUMBER,
    PHONE_NUM NUMBER,
    MAIL_ID VARCHAR2(50),
    DATE_OF_ACTIVE DATE,
    EMP_STATUS VARCHAR2(3)
)
ORGANIZATION EXTERNAL 
( 
TYPE ORACLE_LOADER 
DEFAULT DIRECTORY DATA_PUMP_BSM
ACCESS PARAMETERS 
( 
  RECORDS DELIMITED BY NEWLINE SKIP 1
  NOBADFILE NODISCARDFILE NOLOGFILE
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  MISSING FIELD VALUES ARE NULL
 
  (
    EMP_ID,
    EMP_NAME,
    SALARY,
    ORG_ID,
    PHONE_NUM,
    MAIL_ID,
    DATE_OF_ACTIVE DATE "DD-MM-YYYY",
    EMP_STATUS
  )
) 
LOCATION ('TCS_03_2026_EMPLOYEES.csv') 
) 
REJECT LIMIT UNLIMITED;
-------------------------------------------------
SELECT * FROM EXT_MONTHLY_ORG_EMP_DTLS;
---------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_EMP_CALCULATION AS
  CURSOR C1 IS
    SELECT OD.ORG_ID, OD.ORG_NAME
      FROM MST_ORG_DTLS OD
     WHERE OD.ORG_STATUS = 'A';
  X           BOOLEAN;
  Y           INTEGER;
  Z           BINARY_INTEGER;
  LV_EMP_FILE VARCHAR2(500);
  LV_QUERY    VARCHAR2(1000);
  LN_EXT_SAL  NUMBER;
  LN_EXT_CNT  NUMBER;
  LV_STATUS   VARCHAR2(10);
  LN_DB_SAL   NUMBER;
  LN_DB_CNT   NUMBER;
BEGIN
  DELETE FROM MONTHLY_ORG_SAL_DTLS;

  FOR I IN C1 LOOP
    FOR J IN (SELECT OE.ORG_ID, SUM(OE.SALARY) SUM_SAL, COUNT(*) CNT
                FROM ORG_EMP_DTLS OE
               WHERE OE.EMP_STATUS = 'A'
                 AND OE.ORG_ID = I.ORG_ID
               GROUP BY OE.ORG_ID) LOOP
    
      INSERT INTO MONTHLY_ORG_SAL_DTLS
      VALUES
        (I.ORG_ID,
         TO_CHAR(SYSDATE, 'MM'),
         TO_CHAR(SYSDATE, 'YYYY'),
         J.SUM_SAL,
         J.CNT);
    END LOOP;
  END LOOP;

  DELETE FROM MONTHLY_ORG_SAL_STATUS;

  FOR I IN C1 LOOP
  
    BEGIN
      SELECT MO.TOTAL_SAL, MO.EMPLOYEES_COUNT
        INTO LN_DB_SAL, LN_DB_CNT
        FROM MONTHLY_ORG_SAL_DTLS MO
       WHERE ORG_ID = I.ORG_ID;
    
    
      LV_EMP_FILE := I.ORG_NAME || '_' || TO_CHAR(SYSDATE, 'MM_YYYY') ||
                     '_EMPLOYEES.CSV';
    
      UTL_FILE.FGETATTR('DATA_PUMP_BSM', LV_EMP_FILE, X, Y, Z);
    
      IF NOT X THEN
        RAISE_APPLICATION_ERROR(-20001, I.ORG_NAME || ' FILE NOT FOUND');
      END IF;
    
      LV_QUERY := 'ALTER TABLE EXT_MONTHLY_ORG_EMP_DTLS LOCATION (''' ||
                  LV_EMP_FILE || ''')';
      EXECUTE IMMEDIATE LV_QUERY;
    
      SELECT SUM(SALARY), COUNT(*)
        INTO LN_EXT_SAL, LN_EXT_CNT
        FROM EXT_MONTHLY_ORG_EMP_DTLS;
    
      INSERT INTO MONTHLY_ORG_SAL_STATUS
        (ORG_ID, MONTH, YEAR, AMOUNT_DIFF, EMPLOYEES_DIFF, MOTHLY_STATUS)
      VALUES
        (I.ORG_ID,
         TO_NUMBER(TO_CHAR(SYSDATE, 'MM')),
         TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')),
         
         ABS(LN_DB_SAL - LN_EXT_SAL),
         ABS(LN_DB_CNT - LN_EXT_CNT),
         
         CASE WHEN LN_DB_SAL = LN_EXT_SAL AND LN_DB_CNT = LN_EXT_CNT THEN 'S' ELSE 'F' END);
    
      SELECT MO.MOTHLY_STATUS
        INTO LV_STATUS
        FROM MONTHLY_ORG_SAL_STATUS MO;
      IF LV_STATUS = 'S' THEN
        UPDATE MONTHLY_SAL_CRD_DTLS MS
           SET MS.SAL_GEN_DATE = TRUNC(SYSDATE), MS.SAL_CRD_STATUS = 'C'
         WHERE MS.SAL_GEN_DATE IS NULL
           AND MS.ORG_NAME = I.ORG_NAME;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(I.ORG_NAME || ' - ' || SQLERRM);
      
    END;
  
  END LOOP;

END SP_EMP_CALCULATION;

----------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_EMP_COMPARE AS
  X           BOOLEAN;
  Y           INTEGER;
  Z           BINARY_INTEGER;
  LV_EMP_FILE VARCHAR2(100);
  LV_QUERY    VARCHAR2(1000);
  LV_ORG_FILE VARCHAR2(100);
  CURSOR C1 IS
    SELECT MS.ORG_ID, MD.ORG_NAME
      FROM MONTHLY_ORG_SAL_STATUS MS
      JOIN MST_ORG_DTLS MD
        ON MS.ORG_ID = MD.ORG_ID
     WHERE MS.MOTHLY_STATUS = 'F';
  FO UTL_FILE.file_type;
BEGIN
  FOR I IN C1 LOOP
    LV_EMP_FILE := I.ORG_NAME || '_' || TO_CHAR(SYSDATE, 'MM_YYYY') ||
                   '_EMPLOYEES.CSV';
  
    UTL_FILE.FGETATTR('DATA_PUMP_BSM', LV_EMP_FILE, X, Y, Z);
  
    IF NOT X THEN
      RAISE_APPLICATION_ERROR(-20001, I.ORG_NAME || ' FILE NOT FOUND');
    END IF;
  
    LV_QUERY := 'ALTER TABLE EXT_MONTHLY_ORG_EMP_DTLS LOCATION (''' ||
                LV_EMP_FILE || ''')';
    EXECUTE IMMEDIATE LV_QUERY;
  
    LV_ORG_FILE := 'BANK_MINUS_ORG_' || TO_CHAR(SYSDATE, 'MM_YYYY') ||
                   '.CSV';
  
    FO := UTL_FILE.FOPEN('DATA_PUMP_BSM', LV_ORG_FILE, 'W');
  
    UTL_FILE.PUT_LINE(FO,
                      'EMP_ID,EMP_NAME,SALARY,ORG_ID,PHONE_NUM,MAIL_ID,DATE_OF_ACTIVE,EMP_STATUS');
  
    FOR J IN (SELECT *
                FROM ORG_EMP_DTLS OE
               WHERE OE.ORG_ID = I.ORG_ID
              MINUS
              SELECT *
                FROM EXT_MONTHLY_ORG_EMP_DTLS EM
               WHERE EM.ORG_ID = I.ORG_ID) LOOP
    
      UTL_FILE.PUT_LINE(FO,
                        J.EMP_ID || ',' || J.EMP_NAME || ',' || J.SALARY || ',' ||
                        J.ORG_ID || ',' || J.PHONE_NUM || ',' || J.MAIL_ID || ',' ||
                        J.DATE_OF_ACTIVE || ',' || J.EMP_STATUS);
    END LOOP;
    UTL_FILE.fclose(FO);
  
    LV_ORG_FILE := 'ORG_MINUS_BANK_' || TO_CHAR(SYSDATE, 'MM_YYYY') ||
                   '.CSV';
  
    FO := UTL_FILE.FOPEN('DATA_PUMP_BSM', LV_ORG_FILE, 'W');
  
    UTL_FILE.PUT_LINE(FO,
                      'EMP_ID,EMP_NAME,SALARY,ORG_ID,PHONE_NUM,MAIL_ID,DATE_OF_ACTIVE,EMP_STATUS');
    FOR K IN (SELECT *
                FROM EXT_MONTHLY_ORG_EMP_DTLS EM
               WHERE EM.ORG_ID = I.ORG_ID
              MINUS
              SELECT *
                FROM ORG_EMP_DTLS OE
               WHERE OE.ORG_ID = I.ORG_ID) LOOP
      UTL_FILE.PUT_LINE(FO,
                        K.EMP_ID || ',' || K.EMP_NAME || ',' || K.SALARY || ',' ||
                        K.ORG_ID || ',' || K.PHONE_NUM || ',' || K.MAIL_ID || ',' ||
                        K.DATE_OF_ACTIVE || ',' || K.EMP_STATUS);
    END LOOP;
  
    UTL_FILE.fclose(FO);
  
  END LOOP;
END SP_EMP_COMPARE;

--------------------------------------------------


--VIEWS
--1.VIEW FOR ALL ACTIVE EMPLOYEES
CREATE OR REPLACE VIEW VW_ACTIVE_EMP_DTLS AS 
SELECT EMP_ID, EMP_NAME, SALARY, ORG_ID, PHONE_NUM, MAIL_ID, DATE_OF_ACTIVE, EMP_STATUS
FROM ORG_EMP_DTLS 
WHERE EMP_STATUS = 'A';

--VIEW FOR ACTIVE ORG EMPLOYEES INPUT ORG NAME
CREATE OR REPLACE VIEW VW_ACTIVE_ORG_EMPLOYEES AS 
SELECT MO.ORG_NAME, OE.EMP_ID, OE.EMP_NAME, OE.SALARY, OE.EMP_STATUS
FROM MST_ORG_DTLS MO
JOIN ORG_EMP_DTLS OE
ON MO.ORG_ID = OE.ORG_ID
WHERE OE.EMP_STATUS = 'A';

SELECT * FROM VW_ACTIVE_ORG_EMPLOYEES WHERE ORG_NAME = 'TCS';

--VIEW FOR 'X' STATUS EMPLOYEES.
CREATE OR REPLACE VIEW VW_EX_EMP_INFO AS 
SELECT EMP_ID, EMP_NAME, SALARY, ORG_ID, PHONE_NUM, MAIL_ID, DATE_OF_ACTIVE, EMP_STATUS
FROM ORG_EMP_DTLS 
WHERE EMP_STATUS = 'X';

--VIEW FOR TIE UP COMPANIES
CREATE OR REPLACE VIEW VW_ACTIVE_ORGS AS 
SELECT ORG_ID, ORG_NAME, ORG_PHONE_NUM, ORG_MAIL_ID, ORG_STATUS
FROM MST_ORG_DTLS 
WHERE ORG_STATUS = 'A';


----------------------------------------------------------
--DISPLAY TOTAL SALARY TO BE PAID TO ORG
CREATE OR REPLACE FUNCTION SF_SAL_TO_PAY_ORG(P_ORG VARCHAR2)
RETURN NUMBER
AS
  LN_TOTAL_SAL NUMBER;
BEGIN
  SELECT SUM(MO.TOTAL_SAL)
  INTO LN_TOTAL_SAL
  FROM MONTHLY_ORG_SAL_DTLS MO
  JOIN MST_ORG_DTLS MD
    ON MO.ORG_ID = MD.ORG_ID
  WHERE MD.ORG_NAME = P_ORG
    AND MO.MONTH = TO_NUMBER(TO_CHAR(SYSDATE,'MM'))
    AND MO.YEAR  = TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'));

  RETURN LN_TOTAL_SAL;

EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;
END;

------------------------------------------------------

--FUNCTION TO DISPLAY TOTAL EMPLOYEE COUNT FOR THAT ORG
CREATE OR REPLACE FUNCTION SF_ORG_ACT_EMP(P_ORG VARCHAR2)
RETURN NUMBER
AS
  LN_TOTAL_COUNT NUMBER;
BEGIN
  SELECT SUM(MO.EMPLOYEES_COUNT)
  INTO LN_TOTAL_COUNT
  FROM MONTHLY_ORG_SAL_DTLS MO
  JOIN MST_ORG_DTLS MD
    ON MO.ORG_ID = MD.ORG_ID
  WHERE MD.ORG_NAME = P_ORG;
  
  RETURN LN_TOTAL_COUNT;

EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;
END;

-------------------------------------------------------
--USER CREATION IN SYS
CREATE USER BSM_BACKUP IDENTIFIED BY BSM;

GRANT CONNECT, DBA TO BSM_BACKUP;
--DATA MIGRATION FROM ONE SCHEMA TO ANOTHER SCHEMA.

--STEP 1
CREATE PUBLIC DATABASE LINK BSM_BKP_LINK
CONNECT TO BSM_BACKUP IDENTIFIED BY BSM
USING 'orcl';

--STEP 2 TABLES CREATION IN BSM_BACKUP
CREATE TABLE MST_ORG_DTLS AS 
SELECT * FROM BSM.MST_ORG_DTLS@BSM_BKP_LINK WHERE 1=2;

ALTER TABLE MST_ORG_DTLS ADD MODIFIED_DATE DATE;

SELECT * FROM MST_ORG_DTLS;

CREATE TABLE ORG_EMP_DTLS AS 
SELECT * FROM BSM.ORG_EMP_DTLS@BSM_BKP_LINK WHERE 1=2;

ALTER TABLE ORG_EMP_DTLS ADD MODIFIED_DATE DATE;

SELECT * FROM ORG_EMP_DTLS;

-- STEP 3 DATA MIGRATION FROM BSM TO BSM_BACKUP
CREATE OR REPLACE PROCEDURE SP_BACKUP_X_DATA
AS
BEGIN

  INSERT INTO MST_ORG_DTLS@BSM_BKP_LINK
  (ORG_ID, ORG_NAME, ORG_PHONE_NUM, ORG_MAIL_ID, ORG_ADDRESS,
   ORG_CP_NAME, ORG_CP_MAIL_ID, ORG_DEAL_DATE,
   ORG_NO_OF_EMPLOYEES, ORG_SALARY_DATE, ORG_STATUS, MODIFIED_DATE)

  SELECT ORG_ID, ORG_NAME, ORG_PHONE_NUM, ORG_MAIL_ID, ORG_ADDRESS,
         ORG_CP_NAME, ORG_CP_MAIL_ID, ORG_DEAL_DATE,
         ORG_NO_OF_EMPLOYEES, ORG_SALARY_DATE, ORG_STATUS, SYSDATE
  FROM MST_ORG_DTLS
  WHERE ORG_STATUS = 'X';

  INSERT INTO ORG_EMP_DTLS@BSM_BKP_LINK
  (EMP_ID, EMP_NAME, SALARY, ORG_ID, PHONE_NUM,
   MAIL_ID, DATE_OF_ACTIVE, EMP_STATUS, MODIFIED_DATE)

  SELECT EMP_ID, EMP_NAME, SALARY, ORG_ID, PHONE_NUM,
         MAIL_ID, DATE_OF_ACTIVE, EMP_STATUS, SYSDATE
  FROM ORG_EMP_DTLS
  WHERE EMP_STATUS = 'X';

  COMMIT;

END SP_BACKUP_X_DATA;

--STEP 4 IF DATA IN BSM_BACKUP IS MORE THAN 3YEARS DELETE THEM [PROCEDURE IN BSM_BACKUP]
CREATE OR REPLACE PROCEDURE SP_PURGE_OLD_DATA
AS
BEGIN

  DELETE FROM ORG_EMP_DTLS
  WHERE MODIFIED_DATE < ADD_MONTHS(TRUNC(SYSDATE), -36);

  DELETE FROM MST_ORG_DTLS
  WHERE MODIFIED_DATE < ADD_MONTHS(TRUNC(SYSDATE), -36);

  COMMIT;

END SP_PURGE_OLD_DATA;

------------------------------------------------------------

--MATERIALIZED VIEW
CREATE MATERIALIZED VIEW MV_ORG_EMP_DTLS
REFRESH START WITH SYSDATE+9/24 NEXT (SYSDATE+1)
AS
SELECT MO.ORG_NAME,MO.ORG_DEAL_DATE,MO.ORG_STATUS,OE.EMP_NAME,OE.SALARY,OE.DATE_OF_ACTIVE,OE.EMP_STATUS
 FROM MST_ORG_DTLS MO JOIN ORG_EMP_DTLS OE ON MO.ORG_ID=OE.ORG_ID ORDER BY MO.ORG_NAME;
 
 ------------------------
 --AUDIT TABLES
 CREATE TABLE AUDIT_ORG_DTLS( ORG_NAME VARCHAR2(30),OLD_MODIFIED_DATE DATE, NEW_MODIFIED_DATE DATE,
ACTION_TYPE VARCHAR2(30),STATUS VARCHAR2(3),REMARKS VARCHAR2(30));

CREATE TABLE AUDIT_ORG_EMP_DTLS(ORG_ID NUMBER, EMP_NAME VARCHAR2(30),OLD_SAL NUMBER,
NEW_SAL NUMBER,STATUS VARCHAR2(3),REMARKS VARCHAR2(30));

----------------------------------
CREATE OR REPLACE TRIGGER TRG_ORG_EMP_DTLS
AFTER INSERT OR UPDATE OR DELETE ON ORG_EMP_DTLS
FOR EACH ROW
DECLARE
  LV_REMARKS VARCHAR2(50);
BEGIN

  IF INSERTING THEN
    LV_REMARKS := 'NEW EMPLOYEE ADDED';

    INSERT INTO AUDIT_ORG_EMP_DTLS
    VALUES (:NEW.ORG_ID, :NEW.EMP_NAME, NULL, :NEW.SALARY, :NEW.EMP_STATUS, LV_REMARKS);

  ELSIF UPDATING THEN
    LV_REMARKS := 'SALARY UPDATED';

    INSERT INTO AUDIT_ORG_EMP_DTLS
    VALUES (:NEW.ORG_ID, :NEW.EMP_NAME, :OLD.SALARY, :NEW.SALARY, :NEW.EMP_STATUS, LV_REMARKS);

  ELSIF DELETING THEN
    LV_REMARKS := 'EMPLOYEE DELETED';

    INSERT INTO AUDIT_ORG_EMP_DTLS
    VALUES (:OLD.ORG_ID, :OLD.EMP_NAME, :OLD.SALARY, NULL, :OLD.EMP_STATUS, LV_REMARKS);

  END IF;

END;

----------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_ORG_DTLS
AFTER INSERT OR UPDATE OR DELETE ON MST_ORG_DTLS
FOR EACH ROW
DECLARE
  LV_REMARKS VARCHAR2(50);
BEGIN

  IF INSERTING THEN
    LV_REMARKS := 'NEW COMPANY INSERTED';

    INSERT INTO AUDIT_ORG_DTLS
    (ORG_NAME, OLD_MODIFIED_DATE, NEW_MODIFIED_DATE, ACTION_TYPE, STATUS, REMARKS)
    VALUES
    (
      :NEW.ORG_NAME,
      NULL,
      :NEW.ORG_DEAL_DATE,
      'INSERT',
      :NEW.ORG_STATUS,
      LV_REMARKS
    );

  ELSIF UPDATING THEN
    LV_REMARKS := 'DATA MODIFIED';

    INSERT INTO AUDIT_ORG_DTLS
    (ORG_NAME, OLD_MODIFIED_DATE, NEW_MODIFIED_DATE, ACTION_TYPE, STATUS, REMARKS)
    VALUES
    (
      :NEW.ORG_NAME,
      :OLD.ORG_DEAL_DATE,
      :NEW.ORG_DEAL_DATE,
      'UPDATE',
      :NEW.ORG_STATUS,
      LV_REMARKS
    );

  ELSIF DELETING THEN
    LV_REMARKS := 'DATA DELETED';

    INSERT INTO AUDIT_ORG_DTLS
    (ORG_NAME, OLD_MODIFIED_DATE, NEW_MODIFIED_DATE, ACTION_TYPE, STATUS, REMARKS)
    VALUES
    (
      :OLD.ORG_NAME,
      :OLD.ORG_DEAL_DATE,
      NULL,
      'DELETE',
      :OLD.ORG_STATUS,
      LV_REMARKS
    );

  END IF;

END;

---------------------------------------------------
